@startuml AccountManagement_ClassDiagram

class APIFacade {
  +routeToAccountMgmt(req : Request)
}

class AccountManagement {
  +receiveRequest(action : String)
  +validateInput(data : Map) : Boolean
  +processAction(action : String, data : Map)
  +validateUser() : Boolean
}

class Logins {
  +parseInput(data : Map) Map
  +checkAccountExists() : Boolean
  +tryPassword() : Boolean
  +acceptLoginAttempt() : Boolean
  +createAccount(data : Map)
}

class ChangeUserPass {
  +editPassword() ' uses account decryption'
  +confirmChanges() : Boolean
  +writeToDB(aid : int) : Boolean
}

class DeactivateAccount {
  +confirmDeactivation()
  +deactivateAccount(a : Account)
  +updateRepository(aid : int)
}

interface AccountRepository {
  +create(t : Account)
  +update(t : Account)
  +delete(id : int)
  +deleteInactive()
  +findById(id : int) : Account
  +findAll() : List<Account>
}

entity AccountDB {
  +create(t : Account)
  +update(t : Account)
  +delete(id : int)
  +deleteInactive()
  +findById(id : int) : Account
  +findAll() : List<Account>
}

entity Account {
  -aid : int
  -name : String
  -age : int
  -address : String
  -email : String
  -password : String
  -clearance : String
  -isActive : Boolean
  -createdAt : DateTime
  -updatedAt : DateTime
  +deactivate() : Boolean
  +decrypt(password : String, aid : int) : String
  +encrypt(aid : int)
  +getDetails() : List
}

' each "password" is stored like this:
' example key: 1x2x4x
' example password: balls
' password stored as: 1x2ballsx4x
' ie sandwich password between key 

APIFacade --> AccountManagement
AccountManagement --> Logins
AccountManagement --> ChangeUserPass
AccountManagement --> DeactivateAccount
Logins ..> AccountRepository
ChangeUserPass ..> AccountRepository
DeactivateAccount ..> AccountRepository
AccountDB .up.|> AccountRepository
AccountDB *-right- Account

@enduml